In [ ]:
!pip install -q google_play_scraper
!pip install -q transformers
!pip install -q plotly-express

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 1.3 MB/s eta 0:00:00

In [ ]:
!pip install  pyyaml==5.4.1

Collecting pyyaml==5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [ ]:
from google_play_scraper import app, Sort , reviews_all
import plotly.express as px
import pandas as pd
import numpy as np

In [ ]:
nb_project = reviews_all('englishlearningspeaking.learnenglish.englishskillsbooster',
                         sleep_milliseconds=0,
                         lang='en',
                         country='us',
                         sort=Sort.MOST_RELEVANT )

In [ ]:
print(nb_project)

[{'reviewId': 'a2e44948-28e1-4aa3-8d7b-8fd3a27f8848', 'userName': 'Salman Khan', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocLxnHQLnrsJ_8YQnMTzqBPaKc11wqSntb7974Wr-DYI6-95DA=mo', 'content': "I had tried more than 20 English learning apps like Duolingo, sivi ai learn, hello talk, memories speak but it didn't help me this is the only app that helped me a lot if your English is weak etc. If you can't speak English, you can try it, it will be a good app for you", 'score': 5, 'thumbsUpCount': 276, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 27, 19, 2, 12), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '529b960e-cfe0-4115-a866-599f81dde84d', 'userName': 'Cheikh Ahmadou Mbacke Sarr', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjUu0SSD-6ulkT88ap_oh9hG4uK0tUe6fJROzeegH-1MlN5EOhKc', 'content': "Wow what an app I have no words to tell us how this app is helpful and so interesting when you would like to improve your English Skills. It have several subjects that you can discuss, education job bank and other I'm sure that this app can help you a lot thank you DEV for this app☝️✍️", 'score': 5, 'thumbsUpCount': 344, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 6, 28, 12, 30, 54), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'fea1365e-362f-4237-a53d-780aa123bb3d', 'userName': 'Aaxerich', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKUeOds6c-2sxMC6u6Tg-oxut-WCqNVvnDgNy6hrs4rYAhmQC0=mo', 'content': 'Whoa it is a very good english app but way too much video ads totally ruined the experience and not properly usable . How can i pay for completely ads free version of this app ? Because i cant use this app with way toooo much ads.', 'score': 1, 'thumbsUpCount': 9, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 10, 2, 20, 40, 42), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'da858207-be99-4c1d-801c-a0755a5f818f', 'userName': 'Edlin Soren', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjWTmeoS_t34FlrJc3FTe_JpkW9e_-rfFVU0bHb9rn274Y5ekHVY', 'content': "Very good app for students, it's one of the best English app . there are so many different things to learn in full freee and offline. Love this app makers.", 'score': 5, 'thumbsUpCount': 14, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 8, 13, 10, 51, 21), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '31945d76-8ea1-4c86-a676-5d039523d636', 'userName': 'Hiranmoy Samanta.', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIEwCrKsHFN6MsbKnORUbPD7NP9UpHAolWNzseocM4Nk22OCQ=mo', 'content': "Just a copy-paste basic informations from the web & tons of Ads on every page.Even after that,I'd give it 4 stars if there's much depth or details in the given informations.Why would i install this app if I can get much more from a Class 5 Grammerbook!Uninstalled happily.", 'score': 1, 'thumbsUpCount': 60, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 14, 20, 1, 22), 'replyContent': 'Dear User, we are sorry for the inconvenience. Our app is designed to work entirely offline. No need internet. Enjoy ad free usage anytime!', 'repliedAt': datetime.datetime(2024, 5, 19, 10, 48, 25), 'appVersion': '1.0.4'}, {'reviewId': 'd929fe40-9964-434f-8e4e-8fc25c969ac2', 'userName': 'Kelvin Addo Bortsie', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocLOG_uv_4pmDOIMH3y7dNEjaK53oqo5eTa8r_Zz2HGUXIn8=mo', 'content': 'Wow,such an awesome app ,easy to comprehend ,learn and topics to guide your studies and everything at all to enable ones fluency and exams writing in ones everyday life ,extremely great .', 'score': 5, 'thumbsUpCount': 338, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 2, 21, 56, 31), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'df3d46f9-2c43-49e6-ac95-ba03b364a800', 'userName': 'Shane Timile', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjUgflU9EfvBd96bbZGg1qWsQ0Cn1uPuLKkCQLTQAF3f5nGoSVUy', 'content': "Lovely app. It's got simple and practical presentation(design). No Random irrelevant information. Highly recommended!", 'score': 5, 'thumbsUpCount': 217, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 2, 3, 5, 33), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '60a05f68-f241-412e-bf09-5ce18b951c20', 'userName': 'F', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocK42RFqBrNOl8dx2aFP1SLMm7H5dqICDhGN3etSCKV15FHvnQ=mo', 'content': "As soon as I open the app, I've been hit with an ad. deleted immediately after.", 'score': 1, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 10, 6, 5, 55, 38), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'adc8058b-a74f-453a-90ab-0eda0ce8500f', 'userName': 'Kulbinder Singh', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjXVHFoXju2J1FTP9CK29YXms7ovHLoA5oj_YChCLirs5KQ9tGqg', 'content': 'Wow 😲 This app is very helpful for improving my English language This is a great Application', 'score': 5, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 8, 26, 16, 22, 43), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'ad26ab95-ea84-41c1-9a61-4a00a3117eec', 'userName': 'Khadija Jannat suba', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocL1kFtkOfEw1d3PVe5_XguileQvhGhqhSYZwj4T82NLYjLPng=mo', 'content': 'wow .Really outstanding .The things I need to know all are here .Thanks a lot for providing as such excellent apps for us .Love it💟💟💟', 'score': 5, 'thumbsUpCount': 110, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 4, 14, 17, 17, 35), 'replyContent': 'Thanks for your review! Please recommend our app to your friends, and don’t hesitate to shoot us a note at pixelhubllc@gmail.com if you have any questions.', 'repliedAt': datetime.datetime(2024, 4, 15, 12, 37, 32), 'appVersion': '1.0.4'}, {'reviewId': '8365adf3-9540-4456-9130-a4dfce716d80', 'userName': 'Otabek Sadiridinov', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjVSXAyISJBhG6pAQ6PWEWonqdsJTb8bg2O4LMQmKLjjHdQOcD4', 'content': "You've a good user interface icons! Which icons set you've used for this project main screen?", 'score': 5, 'thumbsUpCount': 2, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 4, 23, 11, 32, 1), 'replyContent': "Thanks. The icons were sourced from https://iconmonstr.com/, which is a website offering a collection of free icons for various projects. It's a fantastic resource for finding high-quality icons without any cost.", 'repliedAt': datetime.datetime(2024, 4, 28, 7, 11, 6), 'appVersion': '1.0.4'}, {'reviewId': 'd1e28223-73e8-489c-b4b3-ae4d8faa63f3', 'userName': 'Muhammad Umair', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIS2Lo2YJUEqhZufHRvrnegSQzVdTE41dBIZqiGKaf_7lRNXQ=mo', 'content': 'Amazing app. It contains so many terms that I have never heard of.', 'score': 5, 'thumbsUpCount': 14, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 9, 15, 35, 57), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '5ff0edaf-4190-47b8-8442-f929679c5eae', 'userName': 'Atiye Victory', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocLShiM9K1kTTfgm5R5F9nStxtHNgEHeYWXAqu3cjB0xch2L=mo', 'content': "It's good and educating. You learn more English phrases", 'score': 3, 'thumbsUpCount': 53, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 12, 9, 13, 35), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'd06c8eec-b9b1-4690-b08b-84e845122fbe', 'userName': 'Abongile Gumede', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocJA-4_dv4LfYhixEvdtFV2yeYVli_xKIXfvksjSYxyYUbPWnA=mo', 'content': "Really good app and can help many kids for homework and study's", 'score': 5, 'thumbsUpCount': 13, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 31, 21, 26, 28), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'fa3d484d-e193-4c56-92ef-a0f4eb84271c', 'userName': 'Wais Ahmadzai', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKXfkMzaAJ1n2kjt7OkECLwUjOy-ZVAuUYgYFP35wFCbSbImw=mo', 'content': 'This app is really good for learning the English language', 'score': 5, 'thumbsUpCount': 4, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 8, 16, 13, 6, 21), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'dabc7756-f8cf-48cf-bc93-adb73ad416b6', 'userName': 'Alvernia Dewi', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjU5LNJrqmiFpIFfq2GqdS3lyZdP8gCZ8GFxkp8Awb9eIgKLayY', 'content': "It's really good. They made an easy description and example", 'score': 5, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 8, 11, 19, 47, 3), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '2437a5bf-04b6-4878-9255-14b8c99686eb', 'userName': 'Mykola Martych', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIRpY1XkIrbNJGzBcqlt-qjADKHFK13XNrt6es-sQav6AcGPw=mo', 'content': 'Thank you very much for a completely free and very useful application.', 'score': 5, 'thumbsUpCount': 19, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 4, 21, 8, 15, 10), 'replyContent': 'Thanks for your review! Please recommend our app to your friends, and don’t hesitate to shoot us a note at pixelhubllc@gmail.com if you have any questions.', 'repliedAt': datetime.datetime(2024, 4, 30, 15, 16, 38), 'appVersion': '1.0.4'}, {'reviewId': 'da29fefa-42b4-4fe1-b65f-ca34c707e555', 'userName': 'Fahad Ali', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjXhpHYJly_4CyESKGG7RkCWXyHE85u54LxscRkapcmkjI_xIKs', 'content': 'This is very helpful App best English Language Course.', 'score': 5, 'thumbsUpCount': 7, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 6, 19, 14, 31, 15), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '14786cf4-94a6-4389-9edd-92ef2d725d70', 'userName': 'Kabale Matsho', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocI59zqZYX98laGeoyizJ3xNfMBCQrznvFq6Rj6ucLfxISlDzg=mo', 'content': 'Good app especially when it comes to developing English you can read without data it is free and you will also develope with this app you can be promoted', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': None, 'at': datetime.datetime(2024, 10, 8, 17, 46, 37), 'replyContent': None, 'repliedAt': None, 'appVersion': None}, {'reviewId': '2c8f20d9-336d-4129-b6b4-ff302bf1977f', 'userName': 'Mercy Adomaa', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocLKwR65R7Hs7ByW3ll-WTqY-u8DabJOO3tMa6GfU-SLtV3m5Q=mo', 'content': "This app is dead good for everyone.... Anyone can use this app.... I couldn't pronounce my name well back in the days but when I met this app... What!!.... Now my elder brother Elsa.... I don't know... He will come to me and he will be like pronounce this word for me for 10 shillings. And I will pronounce it and he will be like you are really a something.... This app is good. I'm even earning money from it.... See...", 'score': 5, 'thumbsUpCount': 221, 'reviewCreatedVersion': '1.0.0', 'at': datetime.datetime(2024, 3, 6, 1, 20, 56), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.0'}, {'reviewId': 'f54f8f48-07ce-411e-8032-cc02ddafe9e9', 'userName': 'Yasser ally Magono', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjVsYsOYiemz4zmqAAqmwb-3gF2Dvmf7psZ5PuSDTD9m1Fi-cgE', 'content': 'can everyone download this sweet thing please! just have it and take a glance whenever you feel like scrolling. it will do a lot good to your brain than most of your social network browsing', 'score': 5, 'thumbsUpCount': 96, 'reviewCreatedVersion': '1.0.0', 'at': datetime.datetime(2024, 4, 3, 7, 58, 19), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.0'}, {'reviewId': 'bbe67873-a690-47fe-b7a4-162200ce8db1', 'userName': 'Fatma Ali', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKCebff0tNFySIsuc9sMWZOFs4sKowifjlUN03RD5wvrtYP=mo', 'content': 'Was helpful to improve and to know more on english language😘', 'score': 5, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 6, 11, 20, 21, 47), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '191ed1ab-c04a-4203-ae31-3733df286cad', 'userName': 'Damari', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocL8AiE-fOvXGuAptrlRSkA7kGW3Zu9ixL7eeJXqUDKnFGG9ww=mo', 'content': 'Annoying and loud full page video ads!', 'score': 1, 'thumbsUpCount': 7, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 27, 12, 45, 27), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '5a92e742-fd93-48a7-85f2-fe9a2923fb85', 'userName': 'Reena Reena', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjVO8anYp-XKsTCpahfl7g2nd336ROyMDVe_YBPlFtj0C0J7HfQ', 'content': "Very nice It's helps to speak English", 'score': 3, 'thumbsUpCount': 1, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 9, 11, 11, 50, 59), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '2a95d87b-0e1d-455a-bdd2-87e810cefe12', 'userName': 'Precious Titilolu', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIseV5fRcxHgUSiJH_wL6uGiJWKa8HBOXz6emRYi0iUKRJTEg=mo', 'content': "It's cool. Can help upgrade in English", 'score': 4, 'thumbsUpCount': 41, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 21, 17, 30, 5), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '6acd25ee-b48b-4c3e-8d61-247b5349aa35', 'userName': 'Lorejanes Rambuyong', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocL6WjHSR1f1oG6WcMcNPxMSHbxqdMm1IECL8o-xAb5khe6qtg=mo', 'content': 'I enjoy it . I learned a lot of things about basic English', 'score': 5, 'thumbsUpCount': 7, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 25, 12, 12, 48), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'f02c8884-db94-4617-a133-058153f6e517', 'userName': 'Eva Tei gud movie', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKe7vqfhOoMxN-zSTHRoXNlhQvy5iBME_9lAb5nJayNfmEjSw=mo', 'content': 'The app is really fantastic and it really helps but some words cannot be found in it.Please increase the vocabularies', 'score': 5, 'thumbsUpCount': 9, 'reviewCreatedVersion': '1.0.0', 'at': datetime.datetime(2024, 4, 30, 15, 46, 14), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.0'}, {'reviewId': '895491da-71ed-483f-99f0-66ff89275a16', 'userName': 'Abdullah Aqeel', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIphNoQJ0W6oAs7jvlGtYtF_LFhRhxs5H93CxcMCc29BTZEtg=mo', 'content': 'Amazing amazing amazing app l ove itttt! Absolutely masterpiece', 'score': 5, 'thumbsUpCount': 4, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 16, 12, 50), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'b282b780-3f56-42e1-bd8c-090d5a25c712', 'userName': 'Damilola Boluwatife', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKaVoQn-k_VtxUciETVAgI4iLEZZvyUnwmHZ7sCScUKBj1nNA=mo', 'content': 'it helps me in many ways such as having conversations with an educated people', 'score': 4, 'thumbsUpCount': 3, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 26, 21, 49, 57), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '4a96ed45-7504-41f4-8ee4-0609c5e368ae', 'userName': 'Ogechi Dorathy', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocI1jwCUW--Wz7U98mTpa9cjqhL-TAd_qQh-7xsvMYcgjE53kA=mo', 'content': 'The most wonderful app I have seen ever.keep up the good work.', 'score': 1, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 7, 14, 19, 42, 25), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '74c6b76e-8bcf-4021-87ba-94890a6b3fc2', 'userName': 'ADEWALE ZAINAB', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocJaY-FWlApAn_nQNR69nvA1P6f_A1bkLmnMTpFQMjwcNQHHvQ=mo', 'content': 'The speech rate is too high', 'score': 2, 'thumbsUpCount': 13, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 4, 27, 14, 34, 2), 'replyContent': 'Thank you for your feedback. We apologize for any inconvenience caused by the high speech rate in our app. We will address this issue promptly to ensure a better user experience. Please rate us 5 stars. It would encourage us to continue improving the app!', 'repliedAt': datetime.datetime(2024, 4, 30, 15, 13, 9), 'appVersion': '1.0.4'}, {'reviewId': '02555062-2499-4cdc-9082-01f16e776dff', 'userName': 'Sapana Karki', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocJo0zfXgJ8nwRHEi1fBYA7oJ63vm-xc5BVhKgSKMHLhNt6VWg=mo', 'content': 'This is best app for me to learn English', 'score': 5, 'thumbsUpCount': 16, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 4, 17, 11, 30, 10), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '2b66598f-a95f-4755-bb0e-e9948b330f5e', 'userName': 'Nthabeleng Mkhondo', 'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjX5gUGCDb1JtE-pBj-qp8HpD4vFYvv89MZipzGgMaOdyGP7HKNZ', 'content': 'This is the best English app I have ever used 🫀 the app have everything', 'score': 5, 'thumbsUpCount': 7, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 6, 15, 12, 59, 59), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '405af173-ba88-41da-aacc-b615cd3e13ed', 'userName': 'Ana Mae', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocJ2UoaYjO-gClLMuc4FXPgPZCT3Zc8okKkOEAffe0evMcQhPQ=mo', 'content': 'If I give 5 stars on this app, believe me this is awesome. I love thissss app so much', 'score': 5, 'thumbsUpCount': 8, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 12, 6, 11, 22), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'fa2c083b-766a-423d-b266-2c06f2e23666', 'userName': 'Oduro Akwasi', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKXiDCiUVpQItJMQT2rSd5qEaD7MRjOAXOBsOGVyDDBpoTnpg=mo', 'content': 'Very nice app, I have been improve by using this app I will like to recommend to everyone', 'score': 5, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 12, 3, 57, 59), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': 'b0e5b221-7019-4bce-a05b-f841e467c713', 'userName': 'Amirtaju Said', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocLxICp0MKVQB79RFIbwrw0ILywMcFvN7xugHuzWcUqbuD_UiAw=mo', 'content': "It is very well I like it I haven't seen just like this so thanks fore every thing", 'score': 5, 'thumbsUpCount': 8, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 3, 19, 52, 5), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '1f0bc5a3-828d-48c0-b301-1ee4304bf826', 'userName': 'Love Makukule', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocJUMoG1riHaXw9BPMdRm3ukZUDHU1r0Tom0pPe_YUPLBFWRgQ=mo', 'content': 'Good and simple to learn', 'score': 5, 'thumbsUpCount': 6, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 5, 22, 0, 6, 4), 'replyContent': None, 'repliedAt': None, 'appVersion': '1.0.4'}, {'reviewId': '40004468-f171-4379-abf6-d0f64d2ac100', 'userName': 'Samarth Maind', 'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKtEM4uDFsZ5ad2yf96jRLttpjnFdMgIOEelNwMgzvKO0l0cg=mo', 'content': 'Fantastic app for english', 'score': 5, 'thumbsUpCount': 1, 'reviewCreatedVersion': '1.0.4', 'at': datetime.datetime(2024, 8, 5, 6, 7, 36), 'replyContent': None,

In [ ]:
df = pd.DataFrame(np.array(nb_project),columns=['review'])
df = df.join(pd.DataFrame(df.pop('review').tolist()))
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,a2e44948-28e1-4aa3-8d7b-8fd3a27f8848,Salman Khan,https://play-lh.googleusercontent.com/a/ACg8oc...,I had tried more than 20 English learning apps...,5,276,1.0.4,2024-07-27 19:02:12,None,NaT,1.0.4
1,529b960e-cfe0-4115-a866-599f81dde84d,Cheikh Ahmadou Mbacke Sarr,https://play-lh.googleusercontent.com/a-/ALV-U...,Wow what an app I have no words to tell us how...,5,344,1.0.4,2024-06-28 12:30:54,None,NaT,1.0.4
2,fea1365e-362f-4237-a53d-780aa123bb3d,Aaxerich,https://play-lh.googleusercontent.com/a/ACg8oc...,Whoa it is a very good english app but way too...,1,9,1.0.4,2024-10-02 20:40:42,None,NaT,1.0.4
3,da858207-be99-4c1d-801c-a0755a5f818f,Edlin Soren,https://play-lh.googleusercontent.com/a-/ALV-U...,"Very good app for students, it's one of the be...",5,14,1.0.4,2024-08-13 10:51:21,None,NaT,1.0.4
4,31945d76-8ea1-4c86-a676-5d039523d636,Hiranmoy Samanta.,https://play-lh.googleusercontent.com/a/ACg8oc...,Just a copy-paste basic informations from the ...,1,60,1.0.4,2024-05-14 20:01:22,"Dear User, we are sorry for the inconvenience....",2024-05-19 10:48:25,1.0.4
...,...,...,...,...,...,...,...,...,...,...,...
322,0c005bf0-b516-4c7b-bea3-3a3210a4e3d7,Shuan Lei,https://play-lh.googleusercontent.com/a-/ALV-U...,Perferct,5,0,None,2024-06-20 22:03:40,None,NaT,None
323,2df33eb6-67d8-41e6-b0a5-ac7c85d27731,Asma nuur 99,https://play-lh.googleusercontent.com/a/ACg8oc...,I like it,5,0,None,2024-09-25 13:26:04,None,NaT,None
324,d725f555-3f71-46af-a2a4-408faa05808f,John Epas,https://play-lh.googleusercontent.com/a/ACg8oc...,Instaling,5,0,None,2024-07-25 00:03:29,None,NaT,None
325,487ab14a-4e9c-46b6-afa8-beb97ba3c507,Lwandile Moyo,https://play-lh.googleusercontent.com/a/ACg8oc...,Introduction writting,5,1,None,2024-04-17 17:44:25,None,NaT,None
326,4484b428-102e-4d40-aef4-14f0410ffe13,Yared Seyoum,https://play-lh.googleusercontent.com/a-/ALV-U...,Well expriences,5,0,None,2024-06-02 10:55:39,None,NaT,None

In [ ]:
df.describe()

ValueError: Cannot describe a DataFrame without columns

In [ ]:
df['thumbsUpCount'].median()

2.0

In [ ]:
df['thumbsUpCount'].mean()

17.420245398773005

In [ ]:
df['score'].mean()

4.435582822085889

In [ ]:
df['score'].median()

5.0

In [ ]:
df['reviewCreatedVersion'].value_counts()

reviewCreatedVersion
1.0.0    123
1.0.4    113
1.0.3      9
Name: count, dtype: int64

In [ ]:
df['content'][0]

"I had tried more than 20 English learning apps like Duolingo, sivi ai learn, hello talk, memories speak but it didn't help me this is the only app that helped me a lot if your English is weak etc. If you can't speak English, you can try it, it will be a good app for you"

In [ ]:
df.dtypes

reviewId                        object
userName                        object
userImage                       object
content                         object
score                            int64
thumbsUpCount                    int64
reviewCreatedVersion            object
at                      datetime64[ns]
replyContent                    object
repliedAt               datetime64[ns]
appVersion                      object
dtype: object

In [ ]:
from transformers import pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model="siebert/sentiment-roberta-large-english")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/256 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
print(sentiment_pipeline('I had tried more than 20 English learning apps like Duolingo, sivi ai learn, hello talk, memories speak but it didnt help me this is the only app that helped me a lot if your English is weak etc. If you cant speak English, you can try it, it will be a good app for you'))

[{'label': 'POSITIVE', 'score': 0.9983611702919006}]

In [ ]:
df['content'] = df['content'].astype(str)
df['content']

0      I had tried more than 20 English learning apps...
1      Whoa it is a very good english app but way too...
2      Wow what an app I have no words to tell us how...
3      Very good app for students, it's one of the be...
4      Just a copy-paste basic informations from the ...
                             ...
321                                             Perferct
322                                            I like it
323                                            Instaling
324                                Introduction writting
325                                      Well expriences
Name: content, Length: 326, dtype: object

In [ ]:
df['result'] = df['content'].apply(lambda x: sentiment_pipeline(x))

In [ ]:
df['result']

0      [{'label': 'POSITIVE', 'score': 0.998425841331...
1      [{'label': 'NEGATIVE', 'score': 0.999503374099...
2      [{'label': 'POSITIVE', 'score': 0.998882949352...
3      [{'label': 'POSITIVE', 'score': 0.998912930488...
4      [{'label': 'NEGATIVE', 'score': 0.999478638172...
                             ...
321    [{'label': 'POSITIVE', 'score': 0.997294843196...
322    [{'label': 'POSITIVE', 'score': 0.998838484287...
323    [{'label': 'POSITIVE', 'score': 0.997821807861...
324    [{'label': 'NEGATIVE', 'score': 0.997369170188...
325    [{'label': 'POSITIVE', 'score': 0.998287379741...
Name: result, Length: 326, dtype: object

In [ ]:
df['result'].value_counts()

result
[{'label': 'POSITIVE', 'score': 0.9984152317047119}]    15
[{'label': 'POSITIVE', 'score': 0.9977694749832153}]     4
[{'label': 'POSITIVE', 'score': 0.9989069700241089}]     3
[{'label': 'POSITIVE', 'score': 0.9987204074859619}]     3
[{'label': 'POSITIVE', 'score': 0.998406708240509}]      2
                                                        ..
[{'label': 'POSITIVE', 'score': 0.9986452460289001}]     1
[{'label': 'POSITIVE', 'score': 0.9986107349395752}]     1
[{'label': 'POSITIVE', 'score': 0.9976963400840759}]     1
[{'label': 'POSITIVE', 'score': 0.9988969564437866}]     1
[{'label': 'POSITIVE', 'score': 0.9982873797416687}]     1
Name: count, Length: 295, dtype: int64

In [ ]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,result
0,a2e44948-28e1-4aa3-8d7b-8fd3a27f8848,Salman Khan,https://play-lh.googleusercontent.com/a/ACg8oc...,I had tried more than 20 English learning apps...,5,267,1.0.4,2024-07-27 19:02:12,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998425841331..."
1,fea1365e-362f-4237-a53d-780aa123bb3d,ΛΛXΞГICĤ,https://play-lh.googleusercontent.com/a/ACg8oc...,Whoa it is a very good english app but way too...,1,6,1.0.4,2024-10-02 20:40:42,None,NaT,1.0.4,"[{'label': 'NEGATIVE', 'score': 0.999503374099..."
2,529b960e-cfe0-4115-a866-599f81dde84d,Cheikh Ahmadou Mbacke Sarr,https://play-lh.googleusercontent.com/a-/ALV-U...,Wow what an app I have no words to tell us how...,5,336,1.0.4,2024-06-28 12:30:54,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998882949352..."
3,da858207-be99-4c1d-801c-a0755a5f818f,Edlin Soren,https://play-lh.googleusercontent.com/a-/ALV-U...,"Very good app for students, it's one of the be...",5,14,1.0.4,2024-08-13 10:51:21,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998912930488..."
4,31945d76-8ea1-4c86-a676-5d039523d636,Hiranmoy Samanta.,https://play-lh.googleusercontent.com/a/ACg8oc...,Just a copy-paste basic informations from the ...,1,60,1.0.4,2024-05-14 20:01:22,"Dear User, we are sorry for the inconvenience....",2024-05-19 10:48:25,1.0.4,"[{'label': 'NEGATIVE', 'score': 0.999478638172..."

In [ ]:
df['result'][0][0]['label']

'POSITIVE'

In [ ]:
df['sentiments'] = df['result'].apply(lambda x: x[0]['label'])
df['sentiments']

0      POSITIVE
1      NEGATIVE
2      POSITIVE
3      POSITIVE
4      NEGATIVE
         ...
321    POSITIVE
322    POSITIVE
323    POSITIVE
324    NEGATIVE
325    POSITIVE
Name: sentiments, Length: 326, dtype: object

In [ ]:
df['score'] = df['result'].apply(lambda x: x[0]['score'])
df['score']

0      0.998426
1      0.999503
2      0.998883
3      0.998913
4      0.999479
         ...
321    0.997295
322    0.998838
323    0.997822
324    0.997369
325    0.998287
Name: score, Length: 326, dtype: float64

In [ ]:
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,result,sentiments
0,a2e44948-28e1-4aa3-8d7b-8fd3a27f8848,Salman Khan,https://play-lh.googleusercontent.com/a/ACg8oc...,I had tried more than 20 English learning apps...,0.998426,267,1.0.4,2024-07-27 19:02:12,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998425841331...",POSITIVE
1,fea1365e-362f-4237-a53d-780aa123bb3d,ΛΛXΞГICĤ,https://play-lh.googleusercontent.com/a/ACg8oc...,Whoa it is a very good english app but way too...,0.999503,6,1.0.4,2024-10-02 20:40:42,None,NaT,1.0.4,"[{'label': 'NEGATIVE', 'score': 0.999503374099...",NEGATIVE
2,529b960e-cfe0-4115-a866-599f81dde84d,Cheikh Ahmadou Mbacke Sarr,https://play-lh.googleusercontent.com/a-/ALV-U...,Wow what an app I have no words to tell us how...,0.998883,336,1.0.4,2024-06-28 12:30:54,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998882949352...",POSITIVE
3,da858207-be99-4c1d-801c-a0755a5f818f,Edlin Soren,https://play-lh.googleusercontent.com/a-/ALV-U...,"Very good app for students, it's one of the be...",0.998913,14,1.0.4,2024-08-13 10:51:21,None,NaT,1.0.4,"[{'label': 'POSITIVE', 'score': 0.998912930488...",POSITIVE
4,31945d76-8ea1-4c86-a676-5d039523d636,Hiranmoy Samanta.,https://play-lh.googleusercontent.com/a/ACg8oc...,Just a copy-paste basic informations from the ...,0.999479,60,1.0.4,2024-05-14 20:01:22,"Dear User, we are sorry for the inconvenience....",2024-05-19 10:48:25,1.0.4,"[{'label': 'NEGATIVE', 'score': 0.999478638172...",NEGATIVE

In [ ]:
df['sentiments'].value_counts(normalize = True)

sentiments
POSITIVE    0.917178
NEGATIVE    0.082822
Name: proportion, dtype: float64

In [ ]:
fig = px.histogram(df, x="sentiments", color = 'sentiments', text_auto = True)
fig.show()

In [ ]:
df.to_csv('E:\web scraping')